services:
  telecord:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    container_name: telecord
    restart: always
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Shanghai
      - YUKIHANA_LOG=true
    volumes:
      - ./data/QQ:/root/.config/QQ